name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Deploy Resrouce group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 9c5bea55-5c55-44fa-87b8-2197cd3adf73
          region: Northeurope
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourcegroupName: rg-githubactions
          subscriptionId: 9c5bea55-5c55-44fa-87b8-2197cd3adf73
          template: ./arm-templates/storageaccount.json
          parameters: ./arm-templates/storageaccount.parameters.json
          deploymentMode: incremental
